-- 1️⃣ Department Table
CREATE TABLE DEPARTMENT (
    DEP_ID INT PRIMARY KEY,
    DEP_NAME VARCHAR(50),
    OFFICE_LOCATION VARCHAR(100)
);

-- 2️⃣ Student Table
CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    GENDER CHAR(1),
    CONTACT_NO VARCHAR(12),
    DEP_ID INT,
    FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);

-- 3️⃣ Faculty Table
CREATE TABLE FACULTY (
    FACULTY_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DESIGNATION VARCHAR(50),
    EMAIL VARCHAR(50),
    DEP_ID INT,
    FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID)
);

-- 4️⃣ Course Table
CREATE TABLE COURSE (
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(30),
    CREDITS INT,
    DEP_ID INT,
    FACULTY_ID INT,
    FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(DEP_ID),
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID)
);

-- 5️⃣ Enrollment Table
CREATE TABLE ENROLLMENT (
    ENROLLMENT_ID INT PRIMARY KEY,
    SEMESTER VARCHAR(10),
    GRADE CHAR(2),
    STUDENT_ID INT,
    COURSE_ID INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

